### ISSUE TITLE
Module Not Found Errors in 01_db.ipynb File

### ISSUE THREAD

**Issue by BDFL669** [qgofer/qgoferutils#7]
Unfortunately, the 01_db.ipynb file encountered multiple 'modules not found' errors when I ran some of the cells. Fortunately, both issues had quick fixes that naturally resolved the errors. For instance, I had to first `!pip install nbdev` for the following line to work.

```
#| hide
from nbdev.showdoc import *
```

I also had to `!pip install black` for the following line to work

```
#| hide
import nbdev; nbdev.nbdev_export()
```

**Comment by acquayefrank** [comment]
@BDFL669  perhaps you could make a PR to fix this. So other devs won't face the same issue:
I prefer using conda since most of the development will be using scientific python libraries.

1: https://docs.anaconda.com/free/miniconda/index.html
2: Create a conda environment called qgoferutils
3: conda install orjson
4: conda install requests
5: conda install nbdev
6: conda install -c conda-forge jupyterlab
7: conda install black

Once all these packages are installed export the environment:

conda env export --from-history | grep -v "^prefix: " > environment.yml

Commit the changes and make a PR.

**Comment by BDFL669** [comment]
Ok lemme work on it

**Comment by acquayefrank** [comment]
I just realized -from-history  does not include pip stuff:

So this may be a better solution: Based [on](https://github.com/conda/conda/issues/9628#issuecomment-1608913117)

# Extract installed pip packages
pip_packages=$(conda env export | grep -A9999 ".*- pip:" | grep -v "^prefix: ")

# Export conda environment without builds, and append pip packages
conda env export --from-history | grep -v "^prefix: " > environment.yml
echo "$pip_packages" >> environment.yml

I'll convert that into a bash script in a bit

**Comment by BDFL669** [comment]
I am a Windows user so I had to drop grep from the previous command and
instead used "conda env export --from-history | findstr /V "^prefix: " >
environment.yml". But if --from-history ignores pip installs, then I'll
have to await your direction on this

**Comment by acquayefrank** [comment]
I  guess I'll have to create a bash script and a powershell script for this
